INSERT INTO sorular (soru_metni, secenek_a, secenek_b, secenek_c, secenek_d, dogru_cevap) VALUES
                                                                                              ('1982 Anayasasına göre "Yasama Yetkisi" aşağıdakilerden hangisine aittir?', 'Cumhurbaşkanı', 'TBMM', 'Anayasa Mahkemesi', 'Bakanlar Kurulu', 'TBMM'),
                                                                                              ('657 sayılı Devlet Memurları Kanununa göre, memurlara verilen disiplin cezalarından hangisi için yargı yolu kapalıdır?', 'Uyarma', 'Kınama', 'Aylıktan Kesme', 'Hiçbiri (Hepsine yargı yolu açıktır)', 'Hiçbiri (Hepsine yargı yolu açıktır)'),
                                                                                              ('Resmi Yazışmalarda Uygulanacak Usul ve Esaslar Hakkında Yönetmeliğe göre, yazılarda "Tarih" nereye yazılır?', 'Sayı bloğunun sağına', 'Konu bloğunun altına', 'İmza bloğunun üstüne', 'Muhatap bloğunun altına', 'Sayı bloğunun sağına'),
                                                                                              ('4982 sayılı Bilgi Edinme Hakkı Kanununa göre, kurumlar başvuruya kural olarak kaç iş günü içinde cevap vermelidir?', '7 gün', '10 gün', '15 gün', '30 gün', '15 gün'),
                                                                                              ('Aşağıdakilerden hangisi İdari Yargı mercilerinden biridir?', 'Asliye Hukuk Mahkemesi', 'Danıştay', 'Yargıtay', 'Sulh Ceza Hakimliği', 'Danıştay'),
                                                                                              ('Cumhurbaşkanı seçilebilmek için kaç yaşını doldurmuş olmak gerekir?', '30', '35', '40', '45', '40'),
                                                                                              ('Hatay, hangi yıl Türkiye Cumhuriyeti topraklarına katılmıştır?', '1936', '1938', '1939', '1940', '1939'),
                                                                                              ('UNESCO Dünya Mirası Listesinde yer alan "Göbeklitepe" hangi ilimizdedir?', 'Gaziantep', 'Mardin', 'Şanlıurfa', 'Diyarbakır', 'Şanlıurfa'),
                                                                                              ('Microsoft Word programında yapılan son işlemi geri almak için kullanılan kısayol tuşu hangisidir?', 'CTRL + C', 'CTRL + V', 'CTRL + Z', 'CTRL + X', 'CTRL + Z'),
                                                                                              ('İstiklal Marşımızın yazarı Mehmet Akif Ersoy, marşı nerede kaleme almıştır?', 'Ankara - Taceddin Dergahı', 'İstanbul - Ayasofya', 'Konya - Mevlana Müzesi', 'Burdur - Ulu Cami', 'Ankara - Taceddin Dergahı');